
version: '2.2'

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper_client
    init: true
    container_name: test_zipper_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - zipper
      - storer
    volumes_from:
      - storer-data-container:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  zipper:
    user: zipper
    image: cyberdojo/zipper
    init: true
    container_name: test_zipper_server
    read_only: true
    tmpfs: /tmp
    depends_on:
      - storer
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_ZIPPER_SERVER_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    user: cyber-dojo
    image: cyberdojo/storer
    init: true
    container_name: test_zipper_storer_server
    read_only: true
    tmpfs: /tmp
    depends_on:
      - storer-data-container
    volumes_from:
      - storer-data-container:ro
    environment:
      - CYBER_DOJO_KATAS_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer-data-container:
    image: alpine:latest
    container_name: test-zipper-storer-data-container
    volumes:
      - ./server/katas:${CYBER_DOJO_KATAS_ROOT}:ro
