
version: '2'

volumes:
  tmp_zipper:

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper_client
    container_name: zipper_client
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
    volumes:
      - tmp_zipper:/tmp_zipper:ro
    volumes_from:
      - container:cyber-dojo-zipper-kata-DATA-CONTAINER:ro
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}

  zipper:
    user: nobody
    image: cyberdojo/zipper
    container_name: zipper_server
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_ZIPPER_ROOT
    volumes:
      - tmp_zipper:/tmp_zipper:rw
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_ZIPPER_SERVER_PORT}

  storer:
    user: root
    image: cyberdojo/storer
    container_name: storer_server
    environment:
      - CYBER_DOJO_KATAS_ROOT
    read_only: true
    tmpfs: /tmp
    volumes_from:
      - container:cyber-dojo-zipper-kata-DATA-CONTAINER:rw
