
version: '2.2'

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper_client
    init: true
    container_name: test_zipper_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - zipper
      - storer
    volumes:
      - ./server/test/katas:${CYBER_DOJO_KATAS_ROOT}:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
      - CYBER_DOJO_ZIPPER_SERVICE_NAME
      - CYBER_DOJO_ZIPPER_SERVICE_PORT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test_zipper_server
    read_only: true
    tmpfs: /tmp
    depends_on:
      - storer
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_ZIPPER_SERVICE_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    container_name: test_zipper_storer_server
    read_only: true
    tmpfs: /tmp
    volumes:
      - ./server/test/katas:${CYBER_DOJO_KATAS_ROOT}:ro
    environment:
      - CYBER_DOJO_KATAS_ROOT

