
version: '2'

volumes:
  tmp_zipper:

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper
    container_name: zipper_client
    read_only: true
    tmpfs: /tmp
    environment: [ CYBER_DOJO_ZIPPER_ROOT=/tmp_zipper ]
    volumes: [ "tmp_zipper:/tmp_zipper:ro" ]

  zipper:
    user: nobody
    image: cyberdojo/zipper
    container_name: zipper_server
    environment: [ CYBER_DOJO_ZIPPER_ROOT=/tmp_zipper ]
    read_only: true
    tmpfs: /tmp
    volumes: [ "tmp_zipper:/tmp_zipper:rw" ]
    build:
      context: server
      args: [ PORT=4587 ]

  storer:
    user: root
    image: cyberdojo/storer
    container_name: storer_server
    environment: [ CYBER_DOJO_KATAS_ROOT=/tmp/katas ]
    read_only: true
    tmpfs: /tmp
    volumes_from: [ "container:cyber-dojo-zipper-kata-DATA-CONTAINER:rw" ]
