
version: '2'

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper_client
    container_name: zipper_client
    depends_on:
      - zipper
      - zipper-tmp-container
    volumes_from:
      - storer-data-container:ro
      - zipper-tmp-container:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}


  zipper:
    user: zipper
    image: cyberdojo/zipper
    container_name: zipper_server
    depends_on:
      - storer
      - zipper-tmp-container
    volumes_from:
      - zipper-tmp-container:rw
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_ZIPPER_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_ZIPPER_SERVER_PORT}


  zipper-tmp-container:
    image: cyberdojo/zipper
    container_name: zipper-tmp-container
    volumes:
      - /tmp_zipper
    command: "chown zipper:zipper /tmp_zipper"


  storer:
    user: nobody
    image: cyberdojo/storer
    container_name: storer_server
    depends_on:
      - storer-data-container
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_KATAS_ROOT
    volumes_from:
      - storer-data-container:ro


  storer-data-container:
    image: cyberdojo/storer
    container_name: storer-data-container
    volumes:
      - ./server/katas:${CYBER_DOJO_KATAS_ROOT}
