
version: '2.2'

services:

  zipper_client:
    build:
      context: client
    user: nobody
    image: cyberdojo/zipper-client
    init: true
    container_name: test-zipper-client
    read_only: true
    tmpfs:
      - /tmp:mode=1777      
    restart: 'no'
    depends_on:
      - zipper
      - saver

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  zipper:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-zipper-server
    ports:
      - 4587:4587
    read_only: true
    tmpfs:
      - /tmp:mode=1777
    restart: 'no'
    depends_on:
      - saver

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-zipper-saver
    read_only: true
    ports:
      - 4537:4537
    restart: 'no'
    depends_on:
      - mapper
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533,mode=1777

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  mapper:
    user: nobody
    image: cyberdojo/mapper
    init: true
    container_name: test-zipper-mapper
    read_only: true
    ports:
      - 4547:4547
    restart: 'no'
    tmpfs:
      - /tmp:uid=65534,gid=65533,mode=1777
    volumes:
      - ./test/data/porter:/porter:ro
