
version: '2'

services:

  zipper_client:
    user: nobody
    image: cyberdojo/zipper_client
    container_name: zipper_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - zipper
      - zipper-client-coverage-container
    volumes_from:
      - storer-data-container:ro
      - zipper-client-coverage-container:rw
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}


  zipper:
    user: zipper
    image: cyberdojo/zipper
    container_name: zipper_server
    read_only: true
    tmpfs: /tmp
    depends_on:
      - storer
      - zipper-server-coverage-container
    volumes_from:
      - zipper-server-coverage-container:rw
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_ZIPPER_SERVER_PORT}


  storer:
    user: nobody
    image: cyberdojo/storer
    container_name: storer_server
    depends_on:
      - storer-data-container
    volumes_from:
      - storer-data-container:ro
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_KATAS_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  zipper-client-coverage-container:
    image: cyberdojo/zipper
    container_name: zipper-client-coverage-container
    volumes:
      - /${CYBER_DOJO_COVERAGE_ROOT}
    command: "chown nobody:nobody ${CYBER_DOJO_COVERAGE_ROOT}"


  zipper-server-coverage-container:
    image: cyberdojo/zipper
    container_name: zipper-server-coverage-container
    volumes:
      - /${CYBER_DOJO_COVERAGE_ROOT}
    command: "chown zipper:zipper ${CYBER_DOJO_COVERAGE_ROOT}"


  storer-data-container:
    image: cyberdojo/storer
    container_name: storer-data-container
    volumes:
      - ./server/katas:${CYBER_DOJO_KATAS_ROOT}:ro
