
version: '2'

services:

  # TODO: Add zipper_client
  # TODO: add shared /tmp/cyber-dojo/zipper to zipper-client and zipper-server

  zipper:
  # TODO:Add downloader_client which can see shared /tmp folder...
    user: nobody
    image: cyberdojo/zipper
    container_name: zipper_server
    build:
      context: server
      args:
        PORT: 4587

  storer:
    user: root
    image: cyberdojo/storer
    container_name: storer_server
    environment: [ CYBER_DOJO_KATAS_ROOT=/tmp/katas ]
    read_only: true
    tmpfs: /tmp
    volumes_from:
      - container:cyber-dojo-zipper-kata-DATA-CONTAINER:rw
