
version: '2.2'

services:

  zipper_client:
    build:
      context: client
      args:
        - CYBER_DOJO_HOME=${CYBER_DOJO_HOME}
        - PORT=${CYBER_DOJO_ZIPPER_CLIENT_PORT}
    user: nobody
    image: cyberdojo/zipper-client
    init: true
    container_name: test-zipper-client
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - zipper
      - storer
    volumes:
      - ./client/test:${CYBER_DOJO_HOME}/test:ro
      - ./katas:${CYBER_DOJO_KATAS_ROOT}:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
      - CYBER_DOJO_KATAS_ROOT
      - CYBER_DOJO_ZIPPER_SERVICE_NAME
      - CYBER_DOJO_ZIPPER_SERVICE_PORT
    ports:
      - ${CYBER_DOJO_ZIPPER_CLIENT_PORT}:${CYBER_DOJO_ZIPPER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  zipper:
    build:
      context: server
      args:
        - CYBER_DOJO_HOME=${CYBER_DOJO_HOME}
        - PORT=${CYBER_DOJO_ZIPPER_SERVICE_PORT}
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-zipper-server
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - storer
    volumes:
      - ./server/test:${CYBER_DOJO_HOME}/test:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    container_name: test-zipper-storer-server
    read_only: true
    tmpfs: /tmp
    volumes:
      - ./katas:${CYBER_DOJO_KATAS_ROOT}:ro
    environment:
      - CYBER_DOJO_KATAS_ROOT

